///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SomeRootEntityResult {
/*
{
  "id": 48,
  "tag": "推荐",
  "is_default_chose": 0,
  "is_commend": 1,
  "is_mcn": 0,
  "has_component": 1
} 
*/

  int id;
  String tag;
  int isDefaultChose;
  int isCommend;
  int isMcn;
  int hasComponent;

  SomeRootEntityResult({
    this.id,
    this.tag,
    this.isDefaultChose,
    this.isCommend,
    this.isMcn,
    this.hasComponent,
  });
  SomeRootEntityResult.fromJson(Map<String, dynamic> json) {
    id = json["id"];
    tag = json["tag"];
    isDefaultChose = json["is_default_chose"];
    isCommend = json["is_commend"];
    isMcn = json["is_mcn"];
    hasComponent = json["has_component"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["tag"] = tag;
    data["is_default_chose"] = isDefaultChose;
    data["is_commend"] = isCommend;
    data["is_mcn"] = isMcn;
    data["has_component"] = hasComponent;
    return data;
  }
}

class SuvListArticleTag {
/*
{
  "errcode": 0,
  "result": [
    {
      "id": 48,
      "tag": "推荐",
      "is_default_chose": 0,
      "is_commend": 1,
      "is_mcn": 0,
      "has_component": 1
    }
  ]
} 
*/

  int errcode;
  List<SomeRootEntityResult> result;

  SuvListArticleTag({
    this.errcode,
    this.result,
  });
  SuvListArticleTag.fromJson(Map<String, dynamic> json) {
    errcode = json["errcode"];
  if (json["result"] != null) {
  var v = json["result"];
  var arr0 = List<SomeRootEntityResult>();
  v.forEach((v) {
  arr0.add(SomeRootEntityResult.fromJson(v));
  });
    result = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["errcode"] = errcode;
    if (result != null) {
      var v = result;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v.toJson());
  });
      data["result"] = arr0;
    }
    return data;
  }
}