///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SomeRootEntityResultNewsNewsListUserAccount {
/*
{
  "uid": "2_56c7bdae0cf26f32186fa65b",
  "roles": 0,
  "nickname": "编辑-周会杰",
  "icon": "https://img.suv666.com/ycyh/account/icon/20181115_1vr21o9rzh1l0.jpg",
  "comment": "就爱说点儿小实话～",
  "status": "N",
  "frozen": 0,
  "e_verify_status": 1,
  "mall_status": 1
} 
*/

  String uid;
  int roles;
  String nickname;
  String icon;
  String comment;
  String status;
  int frozen;
  int eVerifyStatus;
  int mallStatus;

  SomeRootEntityResultNewsNewsListUserAccount({
    this.uid,
    this.roles,
    this.nickname,
    this.icon,
    this.comment,
    this.status,
    this.frozen,
    this.eVerifyStatus,
    this.mallStatus,
  });
  SomeRootEntityResultNewsNewsListUserAccount.fromJson(
      Map<String, dynamic> json) {
    uid = json["uid"];
    roles = json["roles"];
    nickname = json["nickname"];
    icon = json["icon"];
    comment = json["comment"];
    status = json["status"];
    frozen = json["frozen"];
    eVerifyStatus = json["e_verify_status"];
    mallStatus = json["mall_status"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["uid"] = uid;
    data["roles"] = roles;
    data["nickname"] = nickname;
    data["icon"] = icon;
    data["comment"] = comment;
    data["status"] = status;
    data["frozen"] = frozen;
    data["e_verify_status"] = eVerifyStatus;
    data["mall_status"] = mallStatus;
    return data;
  }
}

class SomeRootEntityResultNewsNewsList {
/*
{
  "id": 255004,
  "type": 1,
  "title": "【抢先试驾】奥迪e-tron，最均衡的豪华电动SUV！？",
  "brief": "我不是个电动汽车爱好者，也不认为电动才是未来，但当我得知要去试驾奥迪e-tron的时候，心中还是有点小激动的。因为在见识",
  "article_images": [
    "https://img.suv666.com/test/ycyh/news/detail/v22/20190909022905_htPQbJg1.jpg"
  ],
  "comments_count": 111,
  "read_count_front": 40692,
  "createtime": "2019-09-09 08:17:14",
  "layout_type": 0,
  "video_time": 0,
  "comment_switch": 1,
  "user_account": {
    "uid": "2_56c7bdae0cf26f32186fa65b",
    "roles": 0,
    "nickname": "编辑-周会杰",
    "icon": "https://img.suv666.com/ycyh/account/icon/20181115_1vr21o9rzh1l0.jpg",
    "comment": "就爱说点儿小实话～",
    "status": "N",
    "frozen": 0,
    "e_verify_status": 1,
    "mall_status": 1
  }
} 
*/

  int id;
  int type;
  String title;
  String brief;
  List<String> articleImages;
  int commentsCount;
  int readCountFront;
  String createtime;
  int layoutType;
  int videoTime;
  int commentSwitch;
  SomeRootEntityResultNewsNewsListUserAccount userAccount;

  SomeRootEntityResultNewsNewsList({
    this.id,
    this.type,
    this.title,
    this.brief,
    this.articleImages,
    this.commentsCount,
    this.readCountFront,
    this.createtime,
    this.layoutType,
    this.videoTime,
    this.commentSwitch,
    this.userAccount,
  });
  SomeRootEntityResultNewsNewsList.fromJson(Map<String, dynamic> json) {
    id = json["id"];
    type = json["type"];
    title = json["title"];
    brief = json["brief"];
    if (json["article_images"] != null) {
      var v = json["article_images"];
      var arr0 = List<String>();
      v.forEach((v) {
        arr0.add(v);
      });
      articleImages = arr0;
    }
    commentsCount = json["comments_count"];
    readCountFront = json["read_count_front"];
    createtime = json["createtime"];
    layoutType = json["layout_type"];
    videoTime = json["video_time"];
    commentSwitch = json["comment_switch"];
    userAccount = json["user_account"] != null
        ? SomeRootEntityResultNewsNewsListUserAccount.fromJson(
            json["user_account"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["type"] = type;
    data["title"] = title;
    data["brief"] = brief;
    if (articleImages != null) {
      var v = articleImages;
      var arr0 = List();
      v.forEach((v) {
        arr0.add(v);
      });
      data["article_images"] = arr0;
    }
    data["comments_count"] = commentsCount;
    data["read_count_front"] = readCountFront;
    data["createtime"] = createtime;
    data["layout_type"] = layoutType;
    data["video_time"] = videoTime;
    data["comment_switch"] = commentSwitch;
    if (userAccount != null) {
      data["user_account"] = userAccount.toJson();
    }
    return data;
  }
}

class SomeRootEntityResultNews {
/*
{
  "news_list": [
    {
      "id": 255004,
      "type": 1,
      "title": "【抢先试驾】奥迪e-tron，最均衡的豪华电动SUV！？",
      "brief": "我不是个电动汽车爱好者，也不认为电动才是未来，但当我得知要去试驾奥迪e-tron的时候，心中还是有点小激动的。因为在见识",
      "article_images": [
        "https://img.suv666.com/test/ycyh/news/detail/v22/20190909022905_htPQbJg1.jpg"
      ],
      "comments_count": 111,
      "read_count_front": 40692,
      "createtime": "2019-09-09 08:17:14",
      "layout_type": 0,
      "video_time": 0,
      "comment_switch": 1,
      "user_account": {
        "uid": "2_56c7bdae0cf26f32186fa65b",
        "roles": 0,
        "nickname": "编辑-周会杰",
        "icon": "https://img.suv666.com/ycyh/account/icon/20181115_1vr21o9rzh1l0.jpg",
        "comment": "就爱说点儿小实话～",
        "status": "N",
        "frozen": 0,
        "e_verify_status": 1,
        "mall_status": 1
      }
    }
  ],
  "page_id": 2,
  "page_size": 15,
  "total_size": 30704
} 
*/

  List<SomeRootEntityResultNewsNewsList> newsList;
  int pageId;
  int pageSize;
  int totalSize;

  SomeRootEntityResultNews({
    this.newsList,
    this.pageId,
    this.pageSize,
    this.totalSize,
  });
  SomeRootEntityResultNews.fromJson(Map<String, dynamic> json) {
    if (json["news_list"] != null) {
      var v = json["news_list"];
      var arr0 = List<SomeRootEntityResultNewsNewsList>();
      v.forEach((v) {
        arr0.add(SomeRootEntityResultNewsNewsList.fromJson(v));
      });
      newsList = arr0;
    }
    pageId = json["page_id"];
    pageSize = json["page_size"];
    totalSize = json["total_size"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (newsList != null) {
      var v = newsList;
      var arr0 = List();
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data["news_list"] = arr0;
    }
    data["page_id"] = pageId;
    data["page_size"] = pageSize;
    data["total_size"] = totalSize;
    return data;
  }
}

class SomeRootEntityResultMcnMediaList {
/*
{
  "media_id": "media_152730248134508544",
  "icon": "https://img.suv666.com/test/mcn/user/icon/bc203d0a345bf9fef92f6ad2a7c530ab.jpg",
  "media_name": "爱车兵团",
  "brief": "为你而战，10年以上专业汽车团队，彻底帮你解决一切选车、用车难题！"
} 
*/

  String mediaId;
  String icon;
  String mediaName;
  String brief;

  SomeRootEntityResultMcnMediaList({
    this.mediaId,
    this.icon,
    this.mediaName,
    this.brief,
  });
  SomeRootEntityResultMcnMediaList.fromJson(Map<String, dynamic> json) {
    mediaId = json["media_id"];
    icon = json["icon"];
    mediaName = json["media_name"];
    brief = json["brief"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["media_id"] = mediaId;
    data["icon"] = icon;
    data["media_name"] = mediaName;
    data["brief"] = brief;
    return data;
  }
}

class SomeRootEntityResultOriginalColumnList {
/*
{
  "id": 10,
  "name": "有车试驾",
  "brief": "热门新车值得关注吗？专业汽车编辑抢先试驾给你答案",
  "pc_word_cover": "https://img.suv666.com/ycyh/news/original/4dc74ee3919a2ea62950490d804c9b03.png",
  "pc_backgound_cover": "https://img.suv666.com/ycyh/news/original/234b3e560a9c4bf184b45bba29729cb5.png"
} 
*/

  int id;
  String name;
  String brief;
  String pcWordCover;
  String pcBackgoundCover;

  SomeRootEntityResultOriginalColumnList({
    this.id,
    this.name,
    this.brief,
    this.pcWordCover,
    this.pcBackgoundCover,
  });
  SomeRootEntityResultOriginalColumnList.fromJson(Map<String, dynamic> json) {
    id = json["id"];
    name = json["name"];
    brief = json["brief"];
    pcWordCover = json["pc_word_cover"];
    pcBackgoundCover = json["pc_backgound_cover"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["brief"] = brief;
    data["pc_word_cover"] = pcWordCover;
    data["pc_backgound_cover"] = pcBackgoundCover;
    return data;
  }
}

class SomeRootEntityResult {
/*
{
  "original_column_list": [
    {
      "id": 10,
      "name": "有车试驾",
      "brief": "热门新车值得关注吗？专业汽车编辑抢先试驾给你答案",
      "pc_word_cover": "https://img.suv666.com/ycyh/news/original/4dc74ee3919a2ea62950490d804c9b03.png",
      "pc_backgound_cover": "https://img.suv666.com/ycyh/news/original/234b3e560a9c4bf184b45bba29729cb5.png"
    }
  ],
  "mcn_media_list": [
    {
      "media_id": "media_152730248134508544",
      "icon": "https://img.suv666.com/test/mcn/user/icon/bc203d0a345bf9fef92f6ad2a7c530ab.jpg",
      "media_name": "爱车兵团",
      "brief": "为你而战，10年以上专业汽车团队，彻底帮你解决一切选车、用车难题！"
    }
  ],
  "news": {
    "news_list": [
      {
        "id": 255004,
        "type": 1,
        "title": "【抢先试驾】奥迪e-tron，最均衡的豪华电动SUV！？",
        "brief": "我不是个电动汽车爱好者，也不认为电动才是未来，但当我得知要去试驾奥迪e-tron的时候，心中还是有点小激动的。因为在见识",
        "article_images": [
          "https://img.suv666.com/test/ycyh/news/detail/v22/20190909022905_htPQbJg1.jpg"
        ],
        "comments_count": 111,
        "read_count_front": 40692,
        "createtime": "2019-09-09 08:17:14",
        "layout_type": 0,
        "video_time": 0,
        "comment_switch": 1,
        "user_account": {
          "uid": "2_56c7bdae0cf26f32186fa65b",
          "roles": 0,
          "nickname": "编辑-周会杰",
          "icon": "https://img.suv666.com/ycyh/account/icon/20181115_1vr21o9rzh1l0.jpg",
          "comment": "就爱说点儿小实话～",
          "status": "N",
          "frozen": 0,
          "e_verify_status": 1,
          "mall_status": 1
        }
      }
    ],
    "page_id": 2,
    "page_size": 15,
    "total_size": 30704
  }
} 
*/

  List<SomeRootEntityResultOriginalColumnList> originalColumnList;
  List<SomeRootEntityResultMcnMediaList> mcnMediaList;
  SomeRootEntityResultNews news;

  SomeRootEntityResult({
    this.originalColumnList,
    this.mcnMediaList,
    this.news,
  });
  SomeRootEntityResult.fromJson(Map<String, dynamic> json) {
    if (json["original_column_list"] != null) {
      var v = json["original_column_list"];
      var arr0 = List<SomeRootEntityResultOriginalColumnList>();
      v.forEach((v) {
        arr0.add(SomeRootEntityResultOriginalColumnList.fromJson(v));
      });
      originalColumnList = arr0;
    }
    if (json["mcn_media_list"] != null) {
      var v = json["mcn_media_list"];
      var arr0 = List<SomeRootEntityResultMcnMediaList>();
      v.forEach((v) {
        arr0.add(SomeRootEntityResultMcnMediaList.fromJson(v));
      });
      mcnMediaList = arr0;
    }
    news = json["news"] != null
        ? SomeRootEntityResultNews.fromJson(json["news"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (originalColumnList != null) {
      var v = originalColumnList;
      var arr0 = List();
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data["original_column_list"] = arr0;
    }
    if (mcnMediaList != null) {
      var v = mcnMediaList;
      var arr0 = List();
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data["mcn_media_list"] = arr0;
    }
    if (news != null) {
      data["news"] = news.toJson();
    }
    return data;
  }
}

class SuvNewsPcHomepage {
/*
{
  "errcode": 0,
  "result": {
    "original_column_list": [
      {
        "id": 10,
        "name": "有车试驾",
        "brief": "热门新车值得关注吗？专业汽车编辑抢先试驾给你答案",
        "pc_word_cover": "https://img.suv666.com/ycyh/news/original/4dc74ee3919a2ea62950490d804c9b03.png",
        "pc_backgound_cover": "https://img.suv666.com/ycyh/news/original/234b3e560a9c4bf184b45bba29729cb5.png"
      }
    ],
    "mcn_media_list": [
      {
        "media_id": "media_152730248134508544",
        "icon": "https://img.suv666.com/test/mcn/user/icon/bc203d0a345bf9fef92f6ad2a7c530ab.jpg",
        "media_name": "爱车兵团",
        "brief": "为你而战，10年以上专业汽车团队，彻底帮你解决一切选车、用车难题！"
      }
    ],
    "news": {
      "news_list": [
        {
          "id": 255004,
          "type": 1,
          "title": "【抢先试驾】奥迪e-tron，最均衡的豪华电动SUV！？",
          "brief": "我不是个电动汽车爱好者，也不认为电动才是未来，但当我得知要去试驾奥迪e-tron的时候，心中还是有点小激动的。因为在见识",
          "article_images": [
            "https://img.suv666.com/test/ycyh/news/detail/v22/20190909022905_htPQbJg1.jpg"
          ],
          "comments_count": 111,
          "read_count_front": 40692,
          "createtime": "2019-09-09 08:17:14",
          "layout_type": 0,
          "video_time": 0,
          "comment_switch": 1,
          "user_account": {
            "uid": "2_56c7bdae0cf26f32186fa65b",
            "roles": 0,
            "nickname": "编辑-周会杰",
            "icon": "https://img.suv666.com/ycyh/account/icon/20181115_1vr21o9rzh1l0.jpg",
            "comment": "就爱说点儿小实话～",
            "status": "N",
            "frozen": 0,
            "e_verify_status": 1,
            "mall_status": 1
          }
        }
      ],
      "page_id": 2,
      "page_size": 15,
      "total_size": 30704
    }
  }
} 
*/

  int errcode;
  SomeRootEntityResult result;

  SuvNewsPcHomepage({
    this.errcode,
    this.result,
  });
  SuvNewsPcHomepage.fromJson(Map<String, dynamic> json) {
    errcode = json["errcode"];
    result = json["result"] != null
        ? SomeRootEntityResult.fromJson(json["result"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["errcode"] = errcode;
    if (result != null) {
      data["result"] = result.toJson();
    }
    return data;
  }
}
