///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SomeRootEntityResultNewsListUserAccount {
/*
{
  "uid": "1_5ad6db42e4b035fe61d36841",
  "roles": 0,
  "nickname": "编辑-李长宁",
  "icon": "https://img.suv666.com/ycyh/account/icon/32a43c7af67363edd3f0e3a9b4389da5",
  "comment": "努力为大家带来最快的车讯！",
  "status": "N",
  "frozen": 0,
  "e_verify_status": 1,
  "mall_status": 1
} 
*/

  String uid;
  int roles;
  String nickname;
  String icon;
  String comment;
  String status;
  int frozen;
  int eVerifyStatus;
  int mallStatus;

  SomeRootEntityResultNewsListUserAccount({
    this.uid,
    this.roles,
    this.nickname,
    this.icon,
    this.comment,
    this.status,
    this.frozen,
    this.eVerifyStatus,
    this.mallStatus,
  });
  SomeRootEntityResultNewsListUserAccount.fromJson(Map<String, dynamic> json) {
    uid = json["uid"];
    roles = json["roles"];
    nickname = json["nickname"];
    icon = json["icon"];
    comment = json["comment"];
    status = json["status"];
    frozen = json["frozen"];
    eVerifyStatus = json["e_verify_status"];
    mallStatus = json["mall_status"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["uid"] = uid;
    data["roles"] = roles;
    data["nickname"] = nickname;
    data["icon"] = icon;
    data["comment"] = comment;
    data["status"] = status;
    data["frozen"] = frozen;
    data["e_verify_status"] = eVerifyStatus;
    data["mall_status"] = mallStatus;
    return data;
  }
}

class SomeRootEntityResultNewsList {
/*
{
  "id": 256982,
  "type": 1,
  "title": "【法兰克福车展】最大功率达390马力 实拍新款AMG GLC 43",
  "brief": "",
  "article_images": [
    "https://img.suv666.com/test/ycyh/news/detail/v22/20190910222857_rXnSqTI3.jpg"
  ],
  "comments_count": 819,
  "read_count_front": 39320,
  "createtime": "2019-09-10 22:50:17",
  "layout_type": 1,
  "video_time": 0,
  "comment_switch": 1,
  "user_account": {
    "uid": "1_5ad6db42e4b035fe61d36841",
    "roles": 0,
    "nickname": "编辑-李长宁",
    "icon": "https://img.suv666.com/ycyh/account/icon/32a43c7af67363edd3f0e3a9b4389da5",
    "comment": "努力为大家带来最快的车讯！",
    "status": "N",
    "frozen": 0,
    "e_verify_status": 1,
    "mall_status": 1
  },
  "app_type": 1,
  "wx_author_id": 317,
  "article_type": 2,
  "_score": "51568127017"
} 
*/

  int id;
  int type;
  String title;
  String brief;
  List<String> articleImages;
  int commentsCount;
  int readCountFront;
  String createtime;
  int layoutType;
  int videoTime;
  int commentSwitch;
  SomeRootEntityResultNewsListUserAccount userAccount;
  int appType;
  int wxAuthorId;
  int articleType;
  String score;

  SomeRootEntityResultNewsList({
    this.id,
    this.type,
    this.title,
    this.brief,
    this.articleImages,
    this.commentsCount,
    this.readCountFront,
    this.createtime,
    this.layoutType,
    this.videoTime,
    this.commentSwitch,
    this.userAccount,
    this.appType,
    this.wxAuthorId,
    this.articleType,
    this.score,
  });
  SomeRootEntityResultNewsList.fromJson(Map<String, dynamic> json) {
    id = json["id"];
    type = json["type"];
    title = json["title"];
    brief = json["brief"];
  if (json["article_images"] != null) {
  var v = json["article_images"];
  var arr0 = List<String>();
  v.forEach((v) {
  arr0.add(v);
  });
    articleImages = arr0;
    }
    commentsCount = json["comments_count"];
    readCountFront = json["read_count_front"];
    createtime = json["createtime"];
    layoutType = json["layout_type"];
    videoTime = json["video_time"];
    commentSwitch = json["comment_switch"];
    userAccount = json["user_account"] != null ? SomeRootEntityResultNewsListUserAccount.fromJson(json["user_account"]) : null;
    appType = json["app_type"];
    wxAuthorId = json["wx_author_id"];
    articleType = json["article_type"];
    score = json["_score"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["type"] = type;
    data["title"] = title;
    data["brief"] = brief;
    if (articleImages != null) {
      var v = articleImages;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v);
  });
      data["article_images"] = arr0;
    }
    data["comments_count"] = commentsCount;
    data["read_count_front"] = readCountFront;
    data["createtime"] = createtime;
    data["layout_type"] = layoutType;
    data["video_time"] = videoTime;
    data["comment_switch"] = commentSwitch;
    if (userAccount != null) {
      data["user_account"] = userAccount.toJson();
    }
    data["app_type"] = appType;
    data["wx_author_id"] = wxAuthorId;
    data["article_type"] = articleType;
    data["_score"] = score;
    return data;
  }
}

class SomeRootEntityResultNews {
/*
{
  "list": [
    {
      "id": 256982,
      "type": 1,
      "title": "【法兰克福车展】最大功率达390马力 实拍新款AMG GLC 43",
      "brief": "",
      "article_images": [
        "https://img.suv666.com/test/ycyh/news/detail/v22/20190910222857_rXnSqTI3.jpg"
      ],
      "comments_count": 819,
      "read_count_front": 39320,
      "createtime": "2019-09-10 22:50:17",
      "layout_type": 1,
      "video_time": 0,
      "comment_switch": 1,
      "user_account": {
        "uid": "1_5ad6db42e4b035fe61d36841",
        "roles": 0,
        "nickname": "编辑-李长宁",
        "icon": "https://img.suv666.com/ycyh/account/icon/32a43c7af67363edd3f0e3a9b4389da5",
        "comment": "努力为大家带来最快的车讯！",
        "status": "N",
        "frozen": 0,
        "e_verify_status": 1,
        "mall_status": 1
      },
      "app_type": 1,
      "wx_author_id": 317,
      "article_type": 2,
      "_score": "51568127017"
    }
  ],
  "page_size": 15
} 
*/

  List<SomeRootEntityResultNewsList> list;
  int pageSize;

  SomeRootEntityResultNews({
    this.list,
    this.pageSize,
  });
  SomeRootEntityResultNews.fromJson(Map<String, dynamic> json) {
  if (json["list"] != null) {
  var v = json["list"];
  var arr0 = List<SomeRootEntityResultNewsList>();
  v.forEach((v) {
  arr0.add(SomeRootEntityResultNewsList.fromJson(v));
  });
    list = arr0;
    }
    pageSize = json["page_size"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (list != null) {
      var v = list;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v.toJson());
  });
      data["list"] = arr0;
    }
    data["page_size"] = pageSize;
    return data;
  }
}

class SomeRootEntityResult {
/*
{
  "news": {
    "list": [
      {
        "id": 256982,
        "type": 1,
        "title": "【法兰克福车展】最大功率达390马力 实拍新款AMG GLC 43",
        "brief": "",
        "article_images": [
          "https://img.suv666.com/test/ycyh/news/detail/v22/20190910222857_rXnSqTI3.jpg"
        ],
        "comments_count": 819,
        "read_count_front": 39320,
        "createtime": "2019-09-10 22:50:17",
        "layout_type": 1,
        "video_time": 0,
        "comment_switch": 1,
        "user_account": {
          "uid": "1_5ad6db42e4b035fe61d36841",
          "roles": 0,
          "nickname": "编辑-李长宁",
          "icon": "https://img.suv666.com/ycyh/account/icon/32a43c7af67363edd3f0e3a9b4389da5",
          "comment": "努力为大家带来最快的车讯！",
          "status": "N",
          "frozen": 0,
          "e_verify_status": 1,
          "mall_status": 1
        },
        "app_type": 1,
        "wx_author_id": 317,
        "article_type": 2,
        "_score": "51568127017"
      }
    ],
    "page_size": 15
  }
} 
*/

  SomeRootEntityResultNews news;

  SomeRootEntityResult({
    this.news,
  });
  SomeRootEntityResult.fromJson(Map<String, dynamic> json) {
    news = json["news"] != null ? SomeRootEntityResultNews.fromJson(json["news"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (news != null) {
      data["news"] = news.toJson();
    }
    return data;
  }
}

class SuvPagesV2MainModel {
/*
{
  "errcode": 0,
  "result": {
    "news": {
      "list": [
        {
          "id": 256982,
          "type": 1,
          "title": "【法兰克福车展】最大功率达390马力 实拍新款AMG GLC 43",
          "brief": "",
          "article_images": [
            "https://img.suv666.com/test/ycyh/news/detail/v22/20190910222857_rXnSqTI3.jpg"
          ],
          "comments_count": 819,
          "read_count_front": 39320,
          "createtime": "2019-09-10 22:50:17",
          "layout_type": 1,
          "video_time": 0,
          "comment_switch": 1,
          "user_account": {
            "uid": "1_5ad6db42e4b035fe61d36841",
            "roles": 0,
            "nickname": "编辑-李长宁",
            "icon": "https://img.suv666.com/ycyh/account/icon/32a43c7af67363edd3f0e3a9b4389da5",
            "comment": "努力为大家带来最快的车讯！",
            "status": "N",
            "frozen": 0,
            "e_verify_status": 1,
            "mall_status": 1
          },
          "app_type": 1,
          "wx_author_id": 317,
          "article_type": 2,
          "_score": "51568127017"
        }
      ],
      "page_size": 15
    }
  }
} 
*/

  int errcode;
  SomeRootEntityResult result;

  SuvPagesV2MainModel({
    this.errcode,
    this.result,
  });
  SuvPagesV2MainModel.fromJson(Map<String, dynamic> json) {
    errcode = json["errcode"];
    result = json["result"] != null ? SomeRootEntityResult.fromJson(json["result"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["errcode"] = errcode;
    if (result != null) {
      data["result"] = result.toJson();
    }
    return data;
  }
}
